name: logx
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - -e .
    - click
    - Sphinx
    - coverage
    - awscli
    - flake8
    - python-dotenv>=0.5.1
    - botocore
    - PyYAML<5.3
    - pandas
    - numpy
    - torch
    - tensorboard
    - mlflow
    - sklearn
    - jupyter
    - kedro
    - IPython